steps:
- name: 'hashicorp/terraform:light'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    terraform init &&
    terraform apply -auto-approve

# Optional: Specify a logging option for better traceability
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' # Optional: Adjust machine type if needed for performance
  env:
  - GOOGLE_APPLICATION_CREDENTIALS=service-account.json # Service account file

# Artifacts (optional): Specify if you want to save build artifacts
artifacts:
  objects:
    location: gs://YOUR_PROJECT_ID-cloudbuild-artifacts/
    paths:
    - "*.tfstate" # Save Terraform state files as artifacts (if needed)
