steps:
- name: 'hashicorp/terraform:light'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    terraform init &&
    terraform apply -auto-approve

# Optional: Specify a logging bucket for build logs
options:
  logging: CLOUD_LOGGING_ONLY
