# steps:
# - name: 'hashicorp/terraform:light'
#   entrypoint: '/bin/sh'
#   args:
#   - '-c'
#   - |
#     terraform init

# options:
#   logging: CLOUD_LOGGING_ONLY
# ---------------------------

# steps:
# - name: 'hashicorp/terraform:light'
#   entrypoint: '/bin/sh'
#   args:
#   - '-c'
#   - |
#     terraform init

# - name: 'hashicorp/terraform:light'
#   entrypoint: '/bin/sh'
#   args:
#   - '-c'
#   - |
#     terraform plan -out=tfplan

# options:
#  logging: CLOUD_LOGGING_ONLY
# ---------------------------
steps:
- name: 'hashicorp/terraform:light'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    export GOOGLE_APPLICATION_CREDENTIALS=/workspace/service-account.json &&
    terraform init

- name: 'hashicorp/terraform:light'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    export GOOGLE_APPLICATION_CREDENTIALS=/workspace/service-account.json &&
    terraform plan -out=/workspace/tfplan

- name: 'hashicorp/terraform:light'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    export GOOGLE_APPLICATION_CREDENTIALS=/workspace/service-account.json &&
    terraform apply -auto-approve /workspace/tfplan

options:
  logging: CLOUD_LOGGING_ONLY
