# steps:
# - name: 'hashicorp/terraform:light'
#   entrypoint: '/bin/sh'
#   args:
#   - '-c'
#   - |
#     terraform init

# options:
#   logging: CLOUD_LOGGING_ONLY
# ---------------------------

# steps:
# - name: 'hashicorp/terraform:light'
#   entrypoint: '/bin/sh'
#   args:
#   - '-c'
#   - |
#     terraform init

# - name: 'hashicorp/terraform:light'
#   entrypoint: '/bin/sh'
#   args:
#   - '-c'
#   - |
#     terraform plan -out=tfplan

# options:
#  logging: CLOUD_LOGGING_ONLY
# ---------------------------

steps:
- name: 'hashicorp/terraform:light'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    terraform init

- name: 'hashicorp/terraform:light'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    terraform plan -out=tfplan

- name: 'hashicorp/terraform:light'
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - |
    terraform apply -auto-approve tfplan

options:
  logging: CLOUD_LOGGING_ONLY


