steps:
- name: 'hashicorp/terraform:light'
  entrypoint: '/bin/sh'
  env:
  - "GOOGLE_APPLICATION_CREDENTIALS=service-account.json"
  args:
  - '-c'
  - |
    terraform init &&
    terraform apply -auto-approve


